name: michaelcolenso
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
collections:
  projects:
    output: true
    permalink: /projects/:path/
sass:
  sass_dir: _scss
permalink: none
